name = "vivord-api"
main = "worker.mjs"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "vivo-rd.com/api/*", zone_name = "vivo-rd.com" }
]

[vars]
SITE_URL = "https://vivord2.pages.dev"
ALLOWED_ORIGINS = "https://vivo-rd.com,https://www.vivo-rd.com,https://vivord2.pages.dev"
